#Credentials
GIT_HUB_TOKEN = ""
JIRA_USER_NAME = ""
JIRA_PASSWORD = ""

#Jira Transition IDs
QA_PASSED_ID = "91"
REVIEW_PASSED_ID = "101"
DEPLOY_READY_ID = "111"
PRODUCTION_VERIFIED_ID = "141"

DEBUG = "off"
